language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t multicus/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true multicus/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react-course"
  env: "dockerreactcourse-env"
  bucket_name: "elasticbeanstalk-eu-north-1-836740455247"
  bucket_path: "docker-react-course"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"


#language:generic   # Set at top
# docker run -e CI=true multicus/docker-react npm run test